name: Go Test and Code Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23.2'  # Specify the Go version you are using

      - name: Install dependencies
        run: |
          go mod tidy

      - name: Run tests and collect coverage
        run: |
          go test -v -coverprofile=coverage.out ./...  # Run tests with coverage profile

      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          file: coverage.out  # Path to the coverage report
          token: ${{ secrets.CODECOV_TOKEN }}  # Make sure to add this token in the repository secrets

      - name: Display coverage report
        run: |
          go tool cover -func=coverage.out  # Show the coverage output in the action logs

